monitoring:
  update_interval_ms: 1000
  price_timeout_ms: 5000
  supported_quote_tokens:
    - USDT
    - BUSD
    - USDC

arbitrage:
  min_profit_percentage: 0.5
  min_volume_24h: 100000.0
  min_exchanges_required: 2

exchanges:
  binance:
    enabled: true
    api_key: "${BINANCE_API_KEY:-your_binance_api_key}"
    api_secret: "${BINANCE_API_SECRET:-your_binance_api_secret}"
  kucoin:
    enabled: true
    api_key: "${KUCOIN_API_KEY:-your_kucoin_api_key}"
    api_secret: "${KUCOIN_API_SECRET:-your_kucoin_api_secret}"
    api_passphrase: "${KUCOIN_PASSPHRASE:-your_kucoin_passphrase}"
