name: Rust CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Check formatting
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
        
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings

    - name: Create status file
      if: success()
      run: |
        echo "Last successful build: $(date -u)" > build_status.txt
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add build_status.txt
        git commit -m "Update build status [skip ci]" || echo "No changes to commit"
        git push || echo "No changes to push"
